import React from 'react'

const About = () => {
  return (
    <div name='about' className='w-full h-screen bg-gradient-to-b from-gray-800 to-black text-white'>
      <div className='max-w-screen-lg p-4 mx-auto flex flex-col justify-center w-full h-full'>

        <div className='pb-8'>
          <p className='text-4xl font-bold inline border-b-4 border-gray-500'>About</p>
        </div>
        <p className='text-xl mt-20 sm:text-small'>I am a graduate student at New York University Tandon School of Engineering studying Machine Learning and Data Science where my anticipated graduation date is May 2025. Currently I work at The City University of New York (CUNY) where I mainly use python to clean, manipulate, and present data generated by reports in an orderly fashion with the goal of assisting in making certain business decisions.</p>

        <br />

        <p className='text-xl sm:text-small'>My fascination with computers commenced during my junior year in high school. During this period, I enrolled in my initial college-level computer science course, focused on programming in Java for beginners. In completing each homework assignment, I consistently felt compelled to exceed the prescribed requirements, opting to construct entire programs instead of merely implementing individual functions. It was at this juncture that my academic and vocational aspirations coalesced, solidifying my decision to pursue a field related to computer science in college. Concurrently, I undertook the task of constructing a personal computer, meticulously selecting and researching each component. This experience marked the inception of my enduring enthusiasm for assembling computers, a passion that has persisted, leading me to construct more than ten systems to date.</p>
        <p className='text-xl mt-5 sm:text-small'>Outside of my computer science background, I am a professional table tennis player. At my peak, I was rated top 86 in the United States and top 15 in New York State. I use table tennis experience to share my passion in teaching people to play the sport. Currently, I teach at <a href="http://nisonsttc.com/" className='cursor-pointer text-fuchsia-600'>Nison's Table Tennis Club</a> and at <a href='https://pingpod.com/' className='cursor-pointer text-fuchsia-600'>PingPod</a> where you can book a lesson with me.</p>
      </div>
    </div>
  )
}

export default About